// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcg_KrlG6LTZsOa16mvYr03_qY6mT281Q',
    appId: '1:308358837318:android:76a59643eaf2fa29db4647',
    messagingSenderId: '308358837318',
    projectId: 'ulyana-34cd8',
    databaseURL: 'https://ulyana-34cd8-default-rtdb.firebaseio.com',
    storageBucket: 'ulyana-34cd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdsqLek28374YEZj-4plhqN8xwZGWpjwI',
    appId: '1:308358837318:ios:d0afb00eaac4c46ddb4647',
    messagingSenderId: '308358837318',
    projectId: 'ulyana-34cd8',
    databaseURL: 'https://ulyana-34cd8-default-rtdb.firebaseio.com',
    storageBucket: 'ulyana-34cd8.appspot.com',
    iosClientId: '308358837318-0mkla0rq06pn5rik05kguse3iqbqcfp5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile6Examples',
  );
}
